# yaml_builder.py (Oppdatert versjon)

from typing import List, Dict, Any
import yaml
from dataclasses import asdict

# --- Hjelpefunksjon for å transformere listen ---
def transform_list_to_keyed_dict(instance_list: List[Dict[str, Any]]) -> Dict[str, Dict[str, Any]]:
    """
    Konverterer en liste av dictionaries til én dictionary, 
    hvor verdien av 'name'-feltet blir nøkkelen.
    """
    result_dict = {}
    for item_dict in instance_list:
        if 'name' in item_dict:
            name_key = item_dict['name']
            
            # Kopier dictionaryen og fjern 'name'-feltet
            content_dict = item_dict.copy()
            del content_dict['name']
            
            result_dict[name_key] = content_dict
        else:
            print(f"ADVARSEL: Hopper over objekt uten 'name' felt: {item_dict}")
            
    return result_dict

# --- Rensefunksjon (gjenbrukt fra forrige svar) ---
def clean_data(d):
    """Fjerner felt med None eller tomme lister/dicts rekursivt."""
    if isinstance(d, dict):
        return {k: clean_data(v) for k, v in d.items() if v is not None and v != [] and v != {}}
    if isinstance(d, list):
        return [clean_data(v) for v in d]
    return d

# --- Hovedfunksjonen for YAML-bygging ---
def build_yaml(instances: Dict[str, List[Any]], yaml_filepath: str):
    
    # 1. Konverter alle dataklasse-instanser til rene dictionaries
    processed_data = {}
    for key, instance_list in instances.items():
        dict_list = [asdict(item) for item in instance_list]
        processed_data[key] = dict_list

    # 2. Transformer hver liste (connectors, cables, etc.) til den WireViz-forventede formatet
    #    Hvor 'name'-feltet blir nøkkelen i den nest øverste strukturen.
    final_yaml_dict = {}
    
    for key, dict_list in processed_data.items():
        if not dict_list:
            continue
            
        if key in ['connectors', 'cables']: # Disse WireViz-typene krever navnet som nøkkel
            final_yaml_dict[key] = transform_list_to_keyed_dict(dict_list)
        elif key in ['connections']: # 'connections' er en liste av lister/dictionaries
            # Hent ut 'nodes'-listen fra hver dictionary
            # Før: [{'nodes': [...]}, {'nodes': [...]}] -> Etter: [[...], [...]]
            final_yaml_dict[key] = [item['nodes'] for item in dict_list]
        else:
            # For andre (f.eks. options, custom data)
            final_yaml_dict[key] = dict_list 

    # 3. Rens og skriv til fil
    cleaned_yaml_data = clean_data(final_yaml_dict)
    
    with open(yaml_filepath, "w") as yaml_file:
        yaml_file.write("# WireViz Definition Generated by Python ETL\n\n")

        yaml.dump(
            cleaned_yaml_data, 
            yaml_file,
            sort_keys=False, 
            default_flow_style=False 
        )
        
    print(f"✅ YAML-filen er bygget med WireViz-syntaks og lagret til: {yaml_filepath}")