import yaml
from typing import List, Dict, Any


def _clean_data(d: Any) -> Any:
    """
    Recursively removes fields that are None, or are empty lists/dictionaries.
    WireViz ignores these, but cleaning them up makes the YAML file more readable.
    """
    if isinstance(d, dict):
        return {
            k: _clean_data(v)
            for k, v in d.items()
            if v is not None and v != [] and v != {}
        }
    if isinstance(d, list):
        return [_clean_data(v) for v in d]
    return d


def format_connectors(connector_data: List[Dict[str, Any]]) -> Dict[str, Dict[str, Any]]:
    """
    Formats a list of connector dictionaries into the keyed dictionary
    structure required by WireViz.
    
    Input: [{'name': 'JB1-J1', 'pincount': 4}, {'name': 'JB1-P1', 'pincount': 4}]
    Output: {'JB1-J1': {'pincount': 4}, 'JB1-P1': {'pincount': 4}}
    """
    formatted_connectors = {}
    for connector in connector_data:
        name = connector.pop('name', None)
        if name:
            formatted_connectors[name] = connector
    return formatted_connectors


def format_cables(cable_data: List[Dict[str, Any]]) -> Dict[str, Dict[str, Any]]:
    """
    Formats a list of cable dictionaries into the keyed dictionary
    structure required by WireViz.
    
    Input: [{'name': 'W1', 'wirecount': 2}, {'name': 'W2', 'wirecount': 5}]
    Output: {'W1': {'wirecount': 2}, 'W2': {'wirecount': 5}}
    """
    formatted_cables = {}
    for cable in cable_data:
        name = cable.pop('name', None)
        if name:
            formatted_cables[name] = cable
    return formatted_cables


def format_connections(connection_data: List[Dict[str, Any]]) -> List[List[Dict[str, Any]]]:
    """
    Formats a list of connection dictionaries into the list of lists
    structure required by WireViz.
    
    Input:
    [
        {'from_name': 'J1', 'from_pin': 1, 'to_name': 'P1', 'to_pin': 1, 'name': 'W1', 'via_pin': 1},
        ...
    ]
    
    Output:
    [
        [{'J1': 1}, {'W1': 1}, {'P1': 1}],
        ...
    ]
    """
    formatted = []
    # Group connections by the cable they belong to
    for conn in connection_data:
        from_node = {conn['from_name']: conn['from_pin']}
        to_node = {conn['to_name']: conn['to_pin']}
        via_node = {conn['name']: conn['via_pin']}
        formatted.append([from_node, via_node, to_node])
    return formatted


def build_yaml_file(
    connectors: List[Dict[str, Any]],
    cables: List[Dict[str, Any]],
    connections: List[Dict[str, Any]],
    yaml_filepath: str
) -> None:
    """
    Takes lists of data for connectors, cables, and connections,
    formats them, and writes the final WireViz YAML file.
    """
    final_data = {}

    if connectors:
        final_data['connectors'] = format_connectors(connectors)
    if cables:
        final_data['cables'] = format_cables(cables)
    if connections:
        final_data['connections'] = format_connections(connections)

    # Clean the data for a tidier output file
    cleaned_data = _clean_data(final_data)

    with open(yaml_filepath, "w", encoding="utf-8") as f:
        f.write("# WireViz YAML file generated by WireViz YAML Generator v01\n\n")
        yaml.dump(cleaned_data, f, sort_keys=False, default_flow_style=False, allow_unicode=True)

    print(f"✅ YAML file successfully created at: {yaml_filepath}")